# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjetoMentoria' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjetoMentoria
  pod 'DSM', :git => 'https://github.com/Grupo4Mentoria/DSM.git', :branch => 'feature/fixPodspec'
  pod 'SDKNetwork', :git => 'https://github.com/Grupo4Mentoria/SDKNetwork.git', :branch => 'feature/pod'
  
  pod 'FirebaseAuth'

  target 'ProjetoMentoriaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjetoMentoriaUITests' do
    # Pods for testing
  end

end
